### ISSUE TITLE
Member Page

### ISSUE THREAD

**Issue by curioswati** [justicehub-in/Justice-Hub#14]
**Stories**

* [x] [As a Member I want to see datasets uploaded by me](https://github.com/justicehub-in/Justice-Hub/issues/12)
* [x] [As a member I want to see my profile details](https://github.com/justicehub-in/Justice-Hub/issues/13)
* [x] [As a User I want to get notification emails.](https://github.com/justicehub-in/Justice-Hub/issues/10)
* [ ] [As a User I want to see a visually appealing profile page.](https://github.com/justicehub-in/Justice-Hub/issues/56)
