### ISSUE TITLE
As a User I want to see the number of downloads for each dataset of an Organisation

### ISSUE THREAD

**Issue by curioswati** [justicehub-in/Justice-Hub#20]
**Acceptance Criteria**

When I visit an Organisation's page. I should see the number of downloads for each dataset in the list of datasets.

**Tasks**

* [x] Add palceholder for dataset count
* [x] Check stats plugin for the download count
* [x] Fetch and display download count for datasets

**Comment by curioswati** [comment]
fixed via justicehub-in/ckanext-justicehub_theme@a6dc19de522a779c1a0811603c89ae57241503ae
