### ISSUE TITLE
Partner Page

### ISSUE THREAD

**Issue by curioswati** [justicehub-in/Justice-Hub#23]
**Stories**

* [x] [As a user I want to see all the organisation members at one place](https://github.com/justicehub-in/Justice-Hub/issues/15)

* [x] [As a User I want to see an Organisation's details](https://github.com/justicehub-in/Justice-Hub/issues/16)

* [x] [As a User I want to see all the datasets contributed by an Organisation](https://github.com/justicehub-in/Justice-Hub/issues/17)

* [x] [As a User I want to see the curated datasets of an Organisation](https://github.com/justicehub-in/Justice-Hub/issues/18)

* [x] [As a User I want to see the number of downloads for each dataset of an Organisation](https://github.com/justicehub-in/Justice-Hub/issues/20)

* [x] [As a User I want to see a Partner page which is visually appealing](https://github.com/justicehub-in/Justice-Hub/issues/55)
