### ISSUE TITLE
As a User I want to add Metadata to a dataset I upload

### ISSUE THREAD

**Issue by curioswati** [justicehub-in/Justice-Hub#24]
**Acceptance Criteria**

When I add a dataset, I should be able to add the following metadata to it:

- License
- Update Frequency (how frequently it will be updated)
- Tags
- Author Name
- Author Email
- Geography
  - State
  - District
  - further lower levels if applicable
- Time Interval which the dataset span (e.g. case details for pocso cases `from:` 2015 `to:` 2018)
- Upload date
- Last edited date
- Method of Collection (e.g. Web Scraping, Survey etc)
- Source (e.g. eCourts, NCRB, RTI etc)
- Sensitivity Category
- Assumptions/Notes/Warnings.
- Supplementary Links
- Date of Collection
- Level of the Dataset

**Tasks**

* [x] Create List of sources and show as a dropdown
* [x] [Extend ckanext-validation for custom metadata fields.](https://github.com/justicehub-in/Justice-Hub/issues/26)
* [x] [Supplementary Links as a metadata field.](https://github.com/justicehub-in/Justice-Hub/issues/27)
* [x] [Enable adding multiple external links to a dataset's metadata.](https://github.com/justicehub-in/Justice-Hub/issues/57)
* [x] [add metadata field for capturing the information that a resource represents.](https://github.com/justicehub-in/Justice-Hub/issues/68)
