### ISSUE TITLE
Data Upload

### ISSUE THREAD

**Issue by curioswati** [justicehub-in/Justice-Hub#28]
**Stories**

* [x] [As a User I want to add Metadata to a dataset I upload](https://github.com/justicehub-in/Justice-Hub/issues/24)
* [x] [As a User I want to add license to my dataset.](https://github.com/justicehub-in/Justice-Hub/issues/50)
* [x] [As a User I want to see a visually appealing page to add new datasets](https://github.com/justicehub-in/Justice-Hub/issues/62)
