### ISSUE TITLE
Justice Hub Base Pages

### ISSUE THREAD

**Issue by curioswati** [justicehub-in/Justice-Hub#37]
**Stories**

* [x] [As a User I want to see a home page for data hub.](https://github.com/justicehub-in/Justice-Hub/issues/63)
* [x] [As a User I want to see Header and Footer on the site.](https://github.com/justicehub-in/Justice-Hub/issues/64)
* [x] [As a User I want to see the terms of service.](https://github.com/justicehub-in/Justice-Hub/issues/65)
* [x] [As a User I want to see the Code of Conduct.](https://github.com/justicehub-in/Justice-Hub/issues/66)
